/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ChefIncentivesControllerInterface extends ethers.utils.Interface {
  functions: {
    "addPool(address,uint256)": FunctionFragment;
    "batchUpdateAllocPoint(address[],uint256[])": FunctionFragment;
    "claim(address,address[])": FunctionFragment;
    "claimReceiver(address)": FunctionFragment;
    "claimableReward(address,address[])": FunctionFragment;
    "handleAction(address,uint256,uint256)": FunctionFragment;
    "maxMintableTokens()": FunctionFragment;
    "mintedTokens()": FunctionFragment;
    "owner()": FunctionFragment;
    "poolConfigurator()": FunctionFragment;
    "poolInfo(address)": FunctionFragment;
    "poolLength()": FunctionFragment;
    "registeredTokens(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardMinter()": FunctionFragment;
    "rewardsPerSecond()": FunctionFragment;
    "setClaimReceiver(address,address)": FunctionFragment;
    "setOnwardIncentives(address,address)": FunctionFragment;
    "start()": FunctionFragment;
    "startTime()": FunctionFragment;
    "totalAllocPoint()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userBaseClaimable(address)": FunctionFragment;
    "userInfo(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addPool",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateAllocPoint",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReceiver",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableReward",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "handleAction",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMintableTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolConfigurator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "poolInfo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "poolLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardMinter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardsPerSecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimReceiver",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnwardIncentives",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "start", values?: undefined): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAllocPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userBaseClaimable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "addPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateAllocPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMintableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolLength", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registeredTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardsPerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOnwardIncentives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBaseClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;

  events: {
    "BalanceUpdated(address,address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BalanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ChefIncentivesController extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ChefIncentivesControllerInterface;

  functions: {
    addPool(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addPool(address,uint256)"(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    batchUpdateAllocPoint(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchUpdateAllocPoint(address[],uint256[])"(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claim(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimReceiver(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "claimReceiver(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    claimableReward(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    "claimableReward(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    handleAction(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "handleAction(address,uint256,uint256)"(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    maxMintableTokens(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "maxMintableTokens()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    mintedTokens(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "mintedTokens()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    poolConfigurator(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "poolConfigurator()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    poolInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      totalSupply: BigNumber;
      allocPoint: BigNumber;
      lastRewardTime: BigNumber;
      accRewardPerShare: BigNumber;
      onwardIncentives: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    "poolInfo(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      totalSupply: BigNumber;
      allocPoint: BigNumber;
      lastRewardTime: BigNumber;
      accRewardPerShare: BigNumber;
      onwardIncentives: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    poolLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "poolLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    registeredTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "registeredTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    rewardMinter(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "rewardMinter()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    rewardsPerSecond(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "rewardsPerSecond()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    setClaimReceiver(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setClaimReceiver(address,address)"(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setOnwardIncentives(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setOnwardIncentives(address,address)"(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    start(overrides?: Overrides): Promise<ContractTransaction>;

    "start()"(overrides?: Overrides): Promise<ContractTransaction>;

    startTime(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "startTime()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    totalAllocPoint(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "totalAllocPoint()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userBaseClaimable(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "userBaseClaimable(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    userInfo(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      amount: BigNumber;
      rewardDebt: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "userInfo(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      amount: BigNumber;
      rewardDebt: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  addPool(
    _token: string,
    _allocPoint: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addPool(address,uint256)"(
    _token: string,
    _allocPoint: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  batchUpdateAllocPoint(
    _tokens: string[],
    _allocPoints: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchUpdateAllocPoint(address[],uint256[])"(
    _tokens: string[],
    _allocPoints: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claim(
    _user: string,
    _tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(address,address[])"(
    _user: string,
    _tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimReceiver(arg0: string, overrides?: CallOverrides): Promise<string>;

  "claimReceiver(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  claimableReward(
    _user: string,
    _tokens: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "claimableReward(address,address[])"(
    _user: string,
    _tokens: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  handleAction(
    _user: string,
    _balance: BigNumberish,
    _totalSupply: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "handleAction(address,uint256,uint256)"(
    _user: string,
    _balance: BigNumberish,
    _totalSupply: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  maxMintableTokens(overrides?: CallOverrides): Promise<BigNumber>;

  "maxMintableTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

  mintedTokens(overrides?: CallOverrides): Promise<BigNumber>;

  "mintedTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  poolConfigurator(overrides?: CallOverrides): Promise<string>;

  "poolConfigurator()"(overrides?: CallOverrides): Promise<string>;

  poolInfo(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    totalSupply: BigNumber;
    allocPoint: BigNumber;
    lastRewardTime: BigNumber;
    accRewardPerShare: BigNumber;
    onwardIncentives: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: string;
  }>;

  "poolInfo(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    totalSupply: BigNumber;
    allocPoint: BigNumber;
    lastRewardTime: BigNumber;
    accRewardPerShare: BigNumber;
    onwardIncentives: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: string;
  }>;

  poolLength(overrides?: CallOverrides): Promise<BigNumber>;

  "poolLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  registeredTokens(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "registeredTokens(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  rewardMinter(overrides?: CallOverrides): Promise<string>;

  "rewardMinter()"(overrides?: CallOverrides): Promise<string>;

  rewardsPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

  "rewardsPerSecond()"(overrides?: CallOverrides): Promise<BigNumber>;

  setClaimReceiver(
    _user: string,
    _receiver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setClaimReceiver(address,address)"(
    _user: string,
    _receiver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setOnwardIncentives(
    _token: string,
    _incentives: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setOnwardIncentives(address,address)"(
    _token: string,
    _incentives: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  start(overrides?: Overrides): Promise<ContractTransaction>;

  "start()"(overrides?: Overrides): Promise<ContractTransaction>;

  startTime(overrides?: CallOverrides): Promise<BigNumber>;

  "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalAllocPoint(overrides?: CallOverrides): Promise<BigNumber>;

  "totalAllocPoint()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userBaseClaimable(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userBaseClaimable(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userInfo(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<{
    amount: BigNumber;
    rewardDebt: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "userInfo(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<{
    amount: BigNumber;
    rewardDebt: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  callStatic: {
    addPool(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addPool(address,uint256)"(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    batchUpdateAllocPoint(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchUpdateAllocPoint(address[],uint256[])"(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    claim(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimReceiver(arg0: string, overrides?: CallOverrides): Promise<string>;

    "claimReceiver(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    claimableReward(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "claimableReward(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    handleAction(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "handleAction(address,uint256,uint256)"(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    maxMintableTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "maxMintableTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    mintedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "mintedTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    poolConfigurator(overrides?: CallOverrides): Promise<string>;

    "poolConfigurator()"(overrides?: CallOverrides): Promise<string>;

    poolInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      totalSupply: BigNumber;
      allocPoint: BigNumber;
      lastRewardTime: BigNumber;
      accRewardPerShare: BigNumber;
      onwardIncentives: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    "poolInfo(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      totalSupply: BigNumber;
      allocPoint: BigNumber;
      lastRewardTime: BigNumber;
      accRewardPerShare: BigNumber;
      onwardIncentives: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    poolLength(overrides?: CallOverrides): Promise<BigNumber>;

    "poolLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    registeredTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "registeredTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    rewardMinter(overrides?: CallOverrides): Promise<string>;

    "rewardMinter()"(overrides?: CallOverrides): Promise<string>;

    rewardsPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardsPerSecond()"(overrides?: CallOverrides): Promise<BigNumber>;

    setClaimReceiver(
      _user: string,
      _receiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setClaimReceiver(address,address)"(
      _user: string,
      _receiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOnwardIncentives(
      _token: string,
      _incentives: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setOnwardIncentives(address,address)"(
      _token: string,
      _incentives: string,
      overrides?: CallOverrides
    ): Promise<void>;

    start(overrides?: CallOverrides): Promise<void>;

    "start()"(overrides?: CallOverrides): Promise<void>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalAllocPoint(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAllocPoint()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userBaseClaimable(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userBaseClaimable(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      amount: BigNumber;
      rewardDebt: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "userInfo(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      amount: BigNumber;
      rewardDebt: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  filters: {
    BalanceUpdated(
      token: string | null,
      user: string | null,
      balance: null,
      totalSupply: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    addPool(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addPool(address,uint256)"(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    batchUpdateAllocPoint(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchUpdateAllocPoint(address[],uint256[])"(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    claim(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claim(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimReceiver(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "claimReceiver(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableReward(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "claimableReward(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleAction(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "handleAction(address,uint256,uint256)"(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    maxMintableTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "maxMintableTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    mintedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "mintedTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    poolConfigurator(overrides?: CallOverrides): Promise<BigNumber>;

    "poolConfigurator()"(overrides?: CallOverrides): Promise<BigNumber>;

    poolInfo(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "poolInfo(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolLength(overrides?: CallOverrides): Promise<BigNumber>;

    "poolLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    registeredTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "registeredTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    rewardMinter(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardMinter()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardsPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardsPerSecond()"(overrides?: CallOverrides): Promise<BigNumber>;

    setClaimReceiver(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setClaimReceiver(address,address)"(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setOnwardIncentives(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setOnwardIncentives(address,address)"(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    start(overrides?: Overrides): Promise<BigNumber>;

    "start()"(overrides?: Overrides): Promise<BigNumber>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalAllocPoint(overrides?: CallOverrides): Promise<BigNumber>;

    "totalAllocPoint()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    userBaseClaimable(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userBaseClaimable(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userInfo(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPool(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addPool(address,uint256)"(
      _token: string,
      _allocPoint: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    batchUpdateAllocPoint(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchUpdateAllocPoint(address[],uint256[])"(
      _tokens: string[],
      _allocPoints: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claim(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimReceiver(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "claimReceiver(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimableReward(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "claimableReward(address,address[])"(
      _user: string,
      _tokens: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleAction(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "handleAction(address,uint256,uint256)"(
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    maxMintableTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxMintableTokens()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintedTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mintedTokens()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolConfigurator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "poolConfigurator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "poolInfo(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "poolLength()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registeredTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "registeredTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    rewardMinter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardMinter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardsPerSecond(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardsPerSecond()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setClaimReceiver(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setClaimReceiver(address,address)"(
      _user: string,
      _receiver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setOnwardIncentives(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setOnwardIncentives(address,address)"(
      _token: string,
      _incentives: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    start(overrides?: Overrides): Promise<PopulatedTransaction>;

    "start()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    startTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "startTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAllocPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalAllocPoint()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userBaseClaimable(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userBaseClaimable(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userInfo(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userInfo(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
